name: Node.js CI

on:
  push:
    branches:
      - main # Replace 'main' with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Replace with the desired Node.js version (e.g., 14, 16)

    - name: Install dependencies
      run: npm ci --verbose

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    # Add more steps here for deployment, publishing, etc. as per your project's requirements
